### ISSUE TITLE
Make Req an instance of MonadUnliftIO

### ISSUE THREAD

**Issue by sjshuck** [mrkkrp/req#100]
It seems that the monad-control package is only used to make instances for `MonadBase IO Req` and `MonadBaseControl IO Req`.  Since Req is implemented as a newtype wrapping `ReaderT _something IO`, it's safe to do
```haskell
instance MonadUnliftIO Req where
    withRunInIO = liftBaseWith
```
thereby enabling req consumers following the [ReaderT pattern](https://www.fpcomplete.com/blog/2017/06/readert-design-pattern/) to do all the things possible with monad-control without incurring it as a dependency.
Even if the monad-control instances are offered long-term, for backwards compatibility or any other reason, at least please offer MonadUnliftIO in addition.  The unliftio-core package is tiny and the implementation is just these two lines.
Thanks!

**Comment by mrkkrp** [comment]
I don't mind adding the `MonadUnliftIO` instance in addition to `MonadBase IO Req` and `MonadBaseControl IO Req`. It is somewhat unfortunate to have to support two different solutions to essentially the same problem, but I don't see a better option. The `monad-control` package is older and I don't want to drop support for it just like that—some people may use it.

**Comment by mrkkrp** [comment]
If you want to add the instance, please open a PR.
