### ISSUE TITLE
When req fails with a StatusCodeException the body is truncated

### ISSUE THREAD

**Issue by Zer0-** [mrkkrp/req#104]
There doesn't seem to be a way to get the full body in this case. If an error message is contained in the response body further than the head and script tags it makes it a lot harder to debug the api.

**Comment by mrkkrp** [comment]
The length of body preview is controlled by the `bodyPreviewLength` constant. Would adding a configuration option for that to `HttpConfig` solve the issue for you?

**Comment by Zer0-** [comment]
@mrkkrp, Yes that would solve my issue, thank you.

**Comment by mrkkrp** [comment]
Would you like to open a PR for this?
