### ISSUE TITLE
HanshakeFailed error on archlinux

### ISSUE THREAD

**Issue by geekingfrog** [mrkkrp/req#11]
A minimal reproductible sample: http://lpaste.net/353322
It's working fine on mac OS, but not on archlinux.
I tried with the lower level Network.HTTP.Simple (with the TLS stuff) and got the same error.

Any idea what could go wrong here?

**Comment by mrkkrp** [comment]
Not a `req` issue, I think these are relevant:

* https://github.com/vincenthz/hs-tls/issues/169
* https://github.com/vincenthz/hs-tls/issues/152

It should be fixed in version 1.3.9 of `hs-tls`.

**Comment by geekingfrog** [comment]
Thanks for the links, I'll wait until 1.3.9 is out then.

**Comment by mrkkrp** [comment]
I think it's already on Hackage: https://hackage.haskell.org/package/tls. If you have the same problem with 1.3.9, maybe it makes sense to ask the maintainer.
