### ISSUE TITLE
Add instance of MonadHttp for IO

### ISSUE THREAD

**Issue by mutantmell** [mrkkrp/req#12]
For tutorials, scripts, and code spikes, it would be useful to have a non-orphaned instance of MonadHttp for IO.

**Comment by mrkkrp** [comment]
There is no such instance by design. The instance controls some parameters (like proxy and custom manager settings) that users may want to set differently, we can't set this into stone in the library itself.

If you follow the instructions in the docs and keep your monad abstracted over `MonadHttp` (i.e. you write in this style`myFunc :: MonadHttp m => m ()`) in libraries and only define instances in the end applications, there is no problem orphans could possibly cause.

**Comment by mutantmell** [comment]
I agree that in production code, that application should define a MonadHttp instance for their custom Server type, and they will want the ability to set their Proxy and Customer Manager settings.

This request is more for when I am writing a quick script, or working in the repl, etc.  If the library defined an instance for IO, then I would be able to more easily use the library. Defining a concrete instance for IO would not prevent a user from defining their own instance for a concrete Monad stack, but it would enable users to more easily use it when they don't want that fine-grained control.

**Comment by mrkkrp** [comment]
But their concrete monad stack may be just `IO` as well.

**Comment by mutantmell** [comment]
It's standard practice in Haskell to use a newtype wrapper when you want a new typeclass instance.  Since the recommendation from the library is to leave functions abstracted over MonadHttp, it seems easily amenable to that practice.

I can say that having an instance for IO would have my it easier for me to both learn the library and use it for scripting -- those are situations when I don't care to specify proxy/other custom settings.  Specifically, when I was in the repl, loading my library code (where I do not want to have a concrete MonadHttp instance), it would have been very helpful to have a concrete IO instance defined.

At the end of the day, if you think making sure the user defined their own proxy settings, etc. is worth the initial usability hit, then I would recommend not adding the instance.  From how I've interacted with the library, it would have helped me if there was an instance (and by extension, I think it would help learning in general).

**Comment by mrkkrp** [comment]
Now there is `Req` monad which allows to use `req` in it. You can run it with `runReq` in any IO-enabled monadic stack. Releasing 0.4.0 with this today.
