### ISSUE TITLE
How can I retrieve the exact URL with query parameters? Possible limitation?

### ISSUE THREAD

**Issue by chrissound** [mrkkrp/req#124]
I've got an API that needs the URL (path + query parameters, for example `/example/abc/xyz?a=123`) signed.

However, I don't see any simple way to render such a string for signing (from two values which would be of type `Url` and `Option scheme`). As a workaround I can manually render the string with something like: 

```
qp = [ "a" =: ("123" :: String)]

let url = `/example/abc/xyz` ++ "?" ++ renderQueryParams qp
```

However my concern here would be it's not guaranteed to have the same URL if the `req` library has a different implementation (for example the order of query params are reversed etc).

Also seems to highlight the previous issue mentioned here: https://github.com/mrkkrp/req/issues/74

**Comment by mrkkrp** [comment]
What about `renderUrl`? See https://hackage.haskell.org/package/req-3.9.2/docs/Network-HTTP-Req.html#v:renderUrl

**Comment by chrissound** [comment]
That does not take into account query parameters `Option` - it'd be missing the `?a=123` text?

**Comment by mrkkrp** [comment]
Could you use `URI` from `modern-uri` and then plug it into req via https://hackage.haskell.org/package/req-3.9.2/docs/Network-HTTP-Req.html#v:useURI ?

**Comment by chrissound** [comment]
I could, though it would still (I assume) have the possible issue mentioned here:

> However my concern here would be it's not guaranteed to have the same URL if the req library has a different implementation (for example the order of query params are reversed etc).

**Comment by mrkkrp** [comment]
If you render a `URI` it should produce the same `URI` as you originally parsed, maybe modulo some normalization. You can't use the Req's type safe combinators for constructing `Url`s in that case though.

**Comment by chrissound** [comment]
If I render a URI with the `modern-uri` lib it's not guaranteed that it'll have the same implementation/"render" as `req` as it would be two different implementations right (assuming req does not use modern-uri's render implementation)? I mean it'll likely be fine but it's still not very elegant imo, I'd be worried about edge cases or needing to confirm that the rendered are URLs are always the same otherwise in my case the signing of the URL will fail.

Either way, thanks for the help.
