### ISSUE TITLE
Interface with ToForm and FromForm

### ISSUE THREAD

**Issue by debug-ito** [mrkkrp/req#126]
This is a feature request.

It would be very handy if there was a seemless interface with `ToForm` and `FromForm` typeclasses (in [Web.FormUrlEncoded](https://hackage.haskell.org/package/http-api-data-0.4.3/docs/Web-FormUrlEncoded.html)).

For example,

- req's `FormUrlEncodedParams` can be `ToForm` and `FromForm` instances, I think.
  - Maybe we need to think about how to handle value-less parameters, though.
- A function to convert `ToForm` instance to `QueryParam` instance would be handy, such as

```haskell
import           Network.HTTP.Req    ((=:))
import qualified Network.HTTP.Req    as Req
import qualified Web.FormUrlEncoded  as Form

toReqQuery :: (Form.ToForm a, Req.QueryParam q, Monoid q) => a -> q
toReqQuery a = mconcat $ map (uncurry (=:)) $ Form.toListStable $ Form.toForm a
```

That way, a user could define their own data type as a record, derive its `ToForm` instance and just put it to HTTP requests by req.

**Comment by mrkkrp** [comment]
Great idea! Do you want to open a PR to add this? I imagine it should be quite easy to implement.

**Comment by debug-ito** [comment]
Thanks. I'll try to make a PR, but maybe it takes some time. I'm a little busy with other work.
