### ISSUE TITLE
Support for GHC 9.2

### ISSUE THREAD

**Issue by lilnasy** [mrkkrp/req#128]
- [ ] `hs-memory` is still blocking several packages from supporting GHC 9.2 including `req`. The head hackage repository includes a patch that can be used to update downstream libraries in the meanwhile.
- [ ] The dependency constraint `template-haskell <2.18` is incompatible with the new GHC version. I've tried changing the constraint to `<2.19` and apparently the library compiles and passes the two test suites.
- [ ] GHC 9.2.1 introduces new warnings, including `incomplete-uni-patterns` [GHC#15656](https://gitlab.haskell.org/ghc/ghc/-/issues/15656), which prevents the otherwise passing tests from running since they are set to error on warnings. For example:
```hs
httpbin-tests/Network/HTTP/ReqSpec.hs:138:11: error: [-Wincomplete-uni-patterns, -Werror=incomplete-uni-patterns]
    Pattern match(es) are non-exhaustive
    In a pattern binding:
        Patterns of type ‘Maybe B.ByteString’ not matched: Nothing
    |
138 |       let Just contentType = getRequestContentType body
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I'm new to haskell but I can try creating a PR to fix this warning.

**Comment by mrkkrp** [comment]
Normally warnings should not causes errors. Can you tell me what enables `-Werror` in your case?

**Comment by mrkkrp** [comment]
Closing for now. The `master` is warning-free, but I don't see a reason to release it because normally warnings should not fail the build.
