### ISSUE TITLE
Content-Type MIME based on file

### ISSUE THREAD

**Issue by flip111** [mrkkrp/req#17]
I'm trying to make a new request body type to automatically give a content-type. I call it `ReqBodyMimeFile` and i wanted to use the `magic` package for this. However i need to do [some IO](https://hackage.haskell.org/package/magic-1.1/docs/Magic-Init.html) on the file. How can this be integrated with Req? Or is it better to use an alternative package such as

https://github.com/yesodweb/wai/tree/master/mime-types
or
https://github.com/knrafto/email-header

**Comment by mrkkrp** [comment]
Here is what you need to do:

1. Define your new data type (let's call it `SmartContent`) that will be an instance of `HttpBody`.
2. The data type should contain `RequestBody` (from `http-client`) and also content type as well.
3. Force users to create values of this data type only through a smart constructor, which should live in `IO`-enabled monad, like this: `mkSmartContent :: MonadIO m => FilePath -> m SmartContent`.
4. In `mkSmartContent` you do all the `IO` you want to determine type of the file before you put it into `SmartContent`.
5. Now make `SmartContent` an instance of `HttpBody`, this is easy.

**Comment by flip111** [comment]
Thank you for your feedback!
