### ISSUE TITLE
runReq ignores custom httpConfigAltManager

### ISSUE THREAD

**Issue by d3dave** [mrkkrp/req#27]
A test for `runReq` with non-`def` config is missing. The existing test only checks `def` config.

**Comment by mrkkrp** [comment]
Yes indeed such a test was missing, I fixed it in b7137326407edda0ba59c3e490f31ae967d11b21. However I don't think `runReq` ignores custom `HttpConfig`, the updated test suite proves that. Can you demonstrate a reproducing case where `runReq` indeed ignores `HttpConfig` passed to it?

**Comment by d3dave** [comment]
Hmm. Well, none of the cases check an alternative manager, which is what I'm having an issue with.

**Comment by d3dave** [comment]
```haskell
import Network.HTTP.Req
import Network.HTTP.Client.TLS
import Network.Connection

instance MonadHttp IO where
  handleHttpException = throwIO

newConfig = do
  let noVerifyTlsSettings = TLSSettingsSimple {
    settingDisableCertificateValidation = True,
    settingDisableSession = False,
    settingUseServerName = False
  }
  mgr <- newTlsManagerWith $ mkManagerSettings noVerifyTlsSettings Nothing
  defConfig <- getHttpConfig
  return $ defConfig { httpConfigAltManager = Just mgr }

url = https "localhost" /: "anything"
request = req GET url NoReqBody bsResponse mempty

main :: IO ()
main = do
  config <- newConfig
  resp <- runReq config request
  print $ responseBody resp
```

**Comment by mrkkrp** [comment]
Thanks, I'll look into that tomorrow!

**Comment by mrkkrp** [comment]
Can you please also provide `http-conduit` code that worked for you, for comparison?

**Comment by d3dave** [comment]
Sure. Here is `http-conduit` code that allows the self-signed certificate:

```haskell
import qualified Data.ByteString.Char8 as S8
import qualified Data.ByteString.Lazy.Char8 as L8
import           Network.HTTP.Client
import           Network.HTTP.Client.TLS (mkManagerSettings)
import           Network.HTTP.Simple
import           Network.Connection (TLSSettings(..))

noVerifyTlsManagerSettings = mkManagerSettings noVerifyTlsSettings Nothing
  where
    noVerifyTlsSettings :: TLSSettings
    noVerifyTlsSettings = TLSSettingsSimple
      { settingDisableCertificateValidation = True
      , settingDisableSession = True
      , settingUseServerName = False
      }

main = do
  manager <- newManager noVerifyTlsManagerSettings
  let request
        = setRequestMethod "GET"
        $ setRequestSecure True
        $ setRequestHost "localhost"
        $ setRequestPort 443
        $ setRequestPath "/something"
        $ setRequestManager manager
        $ defaultRequest
  response <- httpLBS request
  putStrLn $ "The status code was: " ++ show (getResponseStatusCode response)
  L8.putStrLn $ getResponseBody response
```

**Comment by mrkkrp** [comment]
I see you have `settingDisableSession = True` in `http-conduit` code and `settingDisableSession = False`, may it be so that this is what is causing the issue with `req`?

I have checked the code, alternative manager should be used with `req` just as well as with `http-conduit`. I could perform more testing if `settingDisableSession` happens to be irrelevant.

**Comment by d3dave** [comment]
Nope, `settingDisableSession = False` with `http-conduit` still works...

**Comment by mrkkrp** [comment]
What about using `newManager` instead of `newTlsManagerWith`. I have set up nginx server locally and made it serve via HTTPS with self signed cert. With `newManager` it works for me with both `http-conduit` an `req`.

**Comment by d3dave** [comment]
Ok. The bug is in `newTlsManagerWith`, as apparently that doesn't work with `http-conduit`. Thanks!

**Comment by d3dave** [comment]
snoyberg/http-client#289
