### ISSUE TITLE
`HttpResponseBody` is not a (visible) associated type of class `HttpResponse`

### ISSUE THREAD

**Issue by ocramz** [mrkkrp/req#28]
It seems HttpResponseBody is not exported by Req ?

I noticed this while writing an HttpResponse that returns Text

**Comment by ocramz** [comment]
I'm not sure this is an issue or not since I imported the whole Req module. Please advise @mrkkrp

**Comment by mrkkrp** [comment]
> It seems HttpResponseBody is not exported by Req ?

I can't reproduce this. Tried to define `TextResponse` in a separate app, everything is in scope. Can you provide a complete reproducing example?

**Comment by mrkkrp** [comment]
Closing for the lack of response. Feel free to re-open if you can demonstrate the problem with a code snippet.

**Comment by ocramz** [comment]
No problem; not even sure what happened the other day. Thanks anyway
