### ISSUE TITLE
AWS Signatures

### ISSUE THREAD

**Issue by GrappigPanda** [mrkkrp/req#31]
I read your section on supporting AWS and was curious if you thought about implementing `UNSIGNED-PAYLOAD` for aws signature generation?

I'm not certain the extent of it's support for various AWS offerings, but, for large uploads to S3, it is common to use `UNSIGNED-PAYLOAD` for signature generation. 

Popular AWS libraries use this, such as boto3 (Python official AWS SDK), jets3t (third-part s3 library), &c.

**Comment by mrkkrp** [comment]
Yes, I'm aware of this option, it's just I personally use `amazonka` for interacting with AWS at the moment and so I don't bother adding this auth option to Req. I'd accept a PR adding that, of course.

**Comment by GrappigPanda** [comment]
Hah, I'd be lost in a Haskell project of any real size--I'm not 100% sure how I ended up on your project, but I just wanted to do my due diligence. Thanks!
