### ISSUE TITLE
Concurrency and Latency

### ISSUE THREAD

**Issue by angerman** [mrkkrp/req#34]
Let's get this out the door first. This is a very nice library to work with!

The documentation is a bit thin on parallelism/concurrency though.  I would
expect that 
```
runReq def $ (,) <$> (req GET ...) <*> (req GET ...)
```
implicitly runs concurrently, is this correct?  Could the documentation be improved
in that regard?

On latency, this might be a bit far stretched, but is it possible to pull the request
latency from req somehow? I know I can set my custom alternative manager and
e.g. set the timeout to 1s instead of 30s. But that's only the upper bound I'd like
to get a handle on the min/max/avg/median request latency for an application that
does a lot of requests.

**Comment by mrkkrp** [comment]
Thanks! No those will run sequentially, just like with `http-client`. You'd need to use something like `async` to make them run in parallel. For latency you could perhaps use `clock` to measure how long the entire `req` business takes, Chris Done has a blog post about this:

http://chrisdone.com/posts/measuring-duration-in-haskell

If you only want to measure time from start of request up to when you get a response you probably could register "end time" in `reqBr` before you stream the response.

**Comment by angerman** [comment]
It seems like meshing with `async` seems to force everthing into IO. Essentially resulting in
```
runConcurrently $ (,) <$> Concurrently (runReq def (req GET ...))
                      <*> Concurrently (runReq def (req GET ...))
```
this seems a bit less elegant than I'd like it to be.

Thanks for the point towards Chris Dones post. I'll look into it!

**Comment by mrkkrp** [comment]
There is also `lifted-async`, although I'd not recommend using it over stateful monadic stacks as a general practice.

**Comment by angerman** [comment]
Ohh right. Completely forgot about `lifted-async`. I'm an idiot, sorry! And yes, state and concurrency almost never play well together :-)

As is, I guess my only request is that the sequential nature of the requests is noted in the documentation, explicitly mentioning that they are not concurrent (to ensure the keyword
is easily found).

Thanks again!

**Comment by mrkkrp** [comment]
I don't know how they possibly can be concurrent, because they return the (actual) response in a monadic context. That means that I can write:

```haskell
main = do
  response <- req GET ...
  if response ....
    then req GET ...foo
    else req GET ...bar
```

Now if there were a possibility of concurrency, I would not be able to write code like this. Just like you cannot write this sort of code with `async` because the concurrent framework only provides you the power of applicative (concurrency-friendly concept), not monad (imposes sequential execution).
