### ISSUE TITLE
Examples encourage use of orphan instances

### ISSUE THREAD

**Issue by rcook** [mrkkrp/req#35]
The first code examples in the documentation suggests doing this as part of the boilerplate:

```
instance MonadHttp IO where
    handleHttpException = throwIO
```

This results in an orphan instance compiler warning:

```
Main.hs:15:1: warning: [-Worphans]
    Orphan instance: instance MonadHttp IO
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.
   |
15 | instance MonadHttp IO where
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

It doesn't sit well for the first sample to result in scary compiler warning.

# Update

I did some more tinkering and it looks like using `runReq` can be used to avoid having to define an orphan instance of `MonadHttp` for `IO`. This, unfortunately, introduces a further package dependency, namely `data-default` since there seems to be no other way to obtain the default value of `HttpConfig`. This leads to the following, warning-free initial example:

```
{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Control.Monad.IO.Class
import Data.Default
import Network.HTTP.Req
import qualified Data.ByteString.Char8 as B

main :: IO ()
main = runReq def $ do
    let n :: Int
        n = 5
    bs <- req GET (https "httpbin.org" /: "bytes" /~ n) NoReqBody bsResponse mempty
    liftIO $ B.putStrLn (responseBody bs)
```

My suggestion would be to update the first examples to demonstrate this usage of the API. I would also consider exporting a new `defaultHttpConfig` function so that users do not need to use `Data.Default.def` and add the `data-default` dependency if they would prefer not to. If you were open to this, I'd be happy to make the changes myself and submit a pull request.

**Comment by mrkkrp** [comment]
I was under the impression that I have already updated all examples to use `runReq` approach. Where do you see

```
instance MonadHttp IO where
    handleHttpException = throwIO
```

?

**Comment by mrkkrp** [comment]
I'm not sure about the  `data-default`-related change. On one hand yes, dropping that dependency is kind of nice. But consider the following:

* By now we can't drop it anyway without releasing new major version. I do not plan to do it yet anyway.
* `data-default-class` is a very lightweight dependency.
* We already use `def` to get the default value and I'd rather avoid having two ways to do the same thing.

In the end, what real problem does elimination of `data-default-class` solve? I'm OK with leaving it as is.

**Comment by rcook** [comment]
Here are the code defines an instance of `MonadHttp` for `IO`:

```
$ git grep -n -C5 'instance MonadHttp IO where'
Network/HTTP/Req.hs-1021---
Network/HTTP/Req.hs-1022--- > import Control.Exception (throwIO)
Network/HTTP/Req.hs-1023--- > import qualified Network.HTTP.Client.MultipartFormData as LM
Network/HTTP/Req.hs-1024--- > import Network.HTTP.Req
Network/HTTP/Req.hs-1025--- >
Network/HTTP/Req.hs:1026:-- > instance MonadHttp IO where
Network/HTTP/Req.hs-1027--- >   handleHttpException = throwIO
Network/HTTP/Req.hs-1028--- >
Network/HTTP/Req.hs-1029--- > main :: IO ()
Network/HTTP/Req.hs-1030--- > main = do
Network/HTTP/Req.hs-1031--- >   body <-
--
httpbin-tests/Network/HTTP/ReqSpec.hs-310-  -- TODO /xml
httpbin-tests/Network/HTTP/ReqSpec.hs-311-
httpbin-tests/Network/HTTP/ReqSpec.hs-312-----------------------------------------------------------------------------
httpbin-tests/Network/HTTP/ReqSpec.hs-313--- Instances
httpbin-tests/Network/HTTP/ReqSpec.hs-314-
httpbin-tests/Network/HTTP/ReqSpec.hs:315:instance MonadHttp IO where
httpbin-tests/Network/HTTP/ReqSpec.hs-316-  handleHttpException = throwIO
httpbin-tests/Network/HTTP/ReqSpec.hs-317-
httpbin-tests/Network/HTTP/ReqSpec.hs-318-----------------------------------------------------------------------------
httpbin-tests/Network/HTTP/ReqSpec.hs-319--- Helpers
httpbin-tests/Network/HTTP/ReqSpec.hs-320-
--
pure-tests/Network/HTTP/ReqSpec.hs-281-          L.requestVersion request `shouldBe` Y.HttpVersion major minor
pure-tests/Network/HTTP/ReqSpec.hs-282-
pure-tests/Network/HTTP/ReqSpec.hs-283-----------------------------------------------------------------------------
pure-tests/Network/HTTP/ReqSpec.hs-284--- Instances
pure-tests/Network/HTTP/ReqSpec.hs-285-
pure-tests/Network/HTTP/ReqSpec.hs:286:instance MonadHttp IO where
pure-tests/Network/HTTP/ReqSpec.hs-287-  handleHttpException = throwIO
pure-tests/Network/HTTP/ReqSpec.hs-288-
pure-tests/Network/HTTP/ReqSpec.hs-289-instance Arbitrary HttpConfig where
pure-tests/Network/HTTP/ReqSpec.hs-290-  arbitrary = do
pure-tests/Network/HTTP/ReqSpec.hs-291-    httpConfigProxy         <- arbitrary
```

**Comment by mrkkrp** [comment]
Thanks. I updated the example for multipart form data in bf30c68, test suites may use orphan instances, there is no harm in that.

**Comment by rcook** [comment]
Works for me!

**Comment by mrkkrp** [comment]
OK, closing then.
