### ISSUE TITLE
SOCKS5 proxy support

### ISSUE THREAD

**Issue by rafagalvez** [mrkkrp/req#39]
Use case
-------------
 Some systems, like the [Tor](https://www.torproject.org) network, expose their client functionality through a local SOCKS5 proxy.

Motivation
---------------

 One of the cool functionalities of Tor is that it provides a mechanism to make servers publicly accessible through a random looking address, whose location is hidden. There is no need for a domain, and you can host the website in any machine running the Tor binary.

 This servers, called [Onion services](https://www.torproject.org/docs/onion-services), have two big advantages over normal web servers:
 - The identity of the user and the location of the server are hidden.
 - They are cheap to deploy and run, as there is no need to register for a domain.

**Comment by mrkkrp** [comment]
Hmm, do you know if this is supported by the `http-client` package? This is a lower-level HTTP client library we build on. So for `req` to support such a feature it would be good to have support for it in  `http-client` first.

**Comment by mrkkrp** [comment]
OK, I'll take a look.

**Comment by mrkkrp** [comment]
OK, to save us both time, here are two simple questions:

1. How do you use the proxy with `http-client`?
2. What prevents you from doing the same with `req`?

So then we just fix 2 and we're done.

From looking at the code, you do 1) by setting an environment variable `http_proxy` or `https_proxy` (should be case-insensitive according to the code but I may be wrong). Have you tried this with `req`?

**Comment by mrkkrp** [comment]
Ping.

**Comment by rafagalvez** [comment]
I'm sorry, I am travelling and time flies :)

So I did test what http-client suggests, and indeed it does not work.
It should, so I dug a bit deeper and they seem to have disabled the
SOCKS5 feature :(

**Comment by mrkkrp** [comment]
As far as I understand this is not a Req issue then, make sure that the feature works with `http-client` and then it should just work with `req`. Closing, re-open if necessary.
