### ISSUE TITLE
Using Proxy with credentials

### ISSUE THREAD

**Issue by rsoeldner** [mrkkrp/req#40]
Is it possible to use a proxy with credentials ? 
I was not able to find something in the documentation

**Comment by mrkkrp** [comment]
How would you use it with `http-client`? Req builds on top of `http-client`, so we need:

1. Find out how to do that with `http-client`.
2. If something in `req` prevents doing the same, fix it` otherwise the problem is non-existent.

**Comment by rsoeldner** [comment]
@mrkkrp Ty, I will check out `http-client` and hopefully come back with a solution 👍

**Comment by mrkkrp** [comment]
Resolved in 6c2c03e68156dbd9ca77e2206d85929961aa5460.
