### ISSUE TITLE
Allow to construct custom Authentication functions?

### ISSUE THREAD

**Issue by angerman** [mrkkrp/req#41]
As it stands `Option` is opaque, and `withRequest` and `asFinalizer` are not part of the public API. As such as a consumer, I can't just define some custom authentication function.

As such building some authenticator that depends on the uri (including the query string) starts to become rather bothersome.

Maybe this could be exposed as `Req.Internal`?

**Comment by mrkkrp** [comment]
Sure, check out #42 and let me know if it solves the problem.
