### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by pradermecker** [mrkkrp/req#45]
Would you mind helping me to convert this curl call to a req one:
```
→ curl -X GET http://puppetdb.prd.srv.cirb.lan:8080/v3/facts --data-urlencode 'query=["=", "certname", "svappcavl841.prd.srv.cirb.lan"]'
```

**Comment by pradermecker** [comment]
I have been trying something like this:
```
getFacts :: IO ()
getFacts = runReq def $ do
  r <- req GET
    (http Config.puppetdbUrl /: "v3" /: "facts")
    NoReqBody
    jsonResponse
    (port 8080) <> ("query" =: [ "=", "certname", "svappcavl841.prd.srv.cirb.lan"] )
  print (responseBody r :: Value)
```
I haven't found one single example of query params that would be representative enough to help me (unlike other libraries that this one is supposed to improve upon).

**Comment by mrkkrp** [comment]
Hi, @pradermecker. I think you want not a query parameter, but request body in URL-encoded form (at least that's what `--data-urlencode` is for in `curl`). Here you go:

https://hackage.haskell.org/package/req-1.1.0/docs/Network-HTTP-Req.html#t:ReqBodyUrlEnc

This is covered in examples for `req` function (click on the `(+) Examples` thing to see them, they are hidden by default in Haddocks, to save space, presumably):

https://hackage.haskell.org/package/req-1.1.0/docs/Network-HTTP-Req.html#v:req

```haskell
main :: IO ()
main = runReq def $ do
  let params =
        "foo" =: ("bar" :: Text) <>
        queryFlag "baz"
  response <- req POST (https "httpbin.org" /: "post") (ReqBodyUrlEnc params) jsonResponse mempty
  liftIO $ print (responseBody response :: Value)
```

**Comment by PierreR** [comment]
@mrkkrp It looks like `ReqBodyUrlEnc` is only valid for `POST`method.

According to https://stackoverflow.com/questions/978061/http-get-with-request-body?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
 it should be valid for the other methods also ?

**Comment by mrkkrp** [comment]
Ah, yeah, I missed the method.
