### ISSUE TITLE
Parsing urls with unknown schema

### ISSUE THREAD

**Issue by waiting-for-dev** [mrkkrp/req#48]
This follows from [a conversation in Haskell Cafe](https://mail.haskell.org/pipermail/haskell-cafe/2018-July/129689.html).

When parsing an URL, I think it is a common scenario not knowing about the schema of the resulting URL. Right now, there are two functions for that purpose:

```haskell
parseUrlHttp :: ByteString -> Maybe (Url Http, Option scheme)
parseUrlHttps :: ByteString -> Maybe (Url Https, Option scheme)
```

Probably, as suggested by Tom Ellis in [one of the messages](https://mail.haskell.org/pipermail/haskell-cafe/2018-July/129697.html), it would make sense having something like:

```haskell
parseUrl :: ByteString -> Maybe (Either (Url Http) (Url Https), Option scheme)
```

Of course it can be done manually, but I think it would make sense in order to avoid some boilerplate.

I'm new to Haskell, but maybe I could try a PR. But in case you find it useful and have the time, don't hesitate to go ahead and implement it.

**Comment by mrkkrp** [comment]
Resolved by #49.
