### ISSUE TITLE
An easy way to avoid throwing on non-200 statuses

### ISSUE THREAD

**Issue by artempyanykh** [mrkkrp/req#52]
With vanilla Network.HTTP.Client one can just `setRequestIgnoreStatus`. It looks like that with *req* I'd need to define `MonadHttp` with `handleHttpException`, but this looks like too much hassle if I just want to run requests in IO and handle all responses irregardless of their status codes.

Am I missing something in the config?

**Comment by mrkkrp** [comment]
This is also shown in the docs and readme 😉

**Comment by artempyanykh** [comment]
@mrkkrp right, just checked Haddock and found mentions of `httpConfigCheckResponse`. However, in README I couldn't find anything except 
> Just define handleHttpException accordingly when making your monad instance of MonadHttp and it will play together seamlessly.

Maybe it's worth adding a small note or example? TBH, I was pretty surprised to receive an exception on non-200 response, not exactly the default of a least surprise.

Anyway, sorry for the silly question. I'm new to Haskell and its ecosystem and failed to figure out from the first try how `http-client` and `req` play together `¯\_(ツ)_/¯`

**Comment by mrkkrp** [comment]
How about the example code?

**Comment by mrkkrp** [comment]
Ah, sorry I just was thinking about `runReq` itself vs defining a new instance. Never mind.
