### ISSUE TITLE
Set Accept "application/json" on jsonResponse

### ISSUE THREAD

**Issue by googleson78** [mrkkrp/req#63]
It seems reasonable that when interpreting the body as `json` we also send a header stating that we accept `application/json`? Is there a reason why this is not the case?

**Comment by mrkkrp** [comment]
Yes it looks like it makes sense. The reason it's not done I guess is simply because in all other cases it didn't make so much sense to send "accept" header and I ended up not including anything for that in the `HttpResponse` class.

Maybe you could try to open a PR implementing the change?
