### ISSUE TITLE
GADT for Url to ensure correctness

### ISSUE THREAD

**Issue by tysonzero** [mrkkrp/req#68]
Currently Url could have a different Scheme at the type level vs the value level. This appears to be hidden from the user due to the un-exported constructor, but I could still see it being beneficial to use a GADT to fully ensure the correctness of this.

**Comment by mrkkrp** [comment]
This could be done, yes. However of no practical consequence, so it's unwise for me to do it when I can find better uses for my time. You're welcome to open a PR which I can promise to merge.

**Comment by mrkkrp** [comment]
I quickly played with this idea and rejected it because I'd need to handle two alternatives every time you pattern-match on `Url` and also deriving of some type classes is impossible with GADTs. Closing.
