### ISSUE TITLE
Returning http or https based on string

### ISSUE THREAD

**Issue by mikesol** [mrkkrp/req#78]
Thanks so much for this incredible library!

I'm trying to write a function that accepts a string and returns either http or https and I'm getting stuck  on getting it to compile. There must be something about the internals of `req` I'm not getting. Any help would be appreciated!

```haskell
schm :: String -> (Text -> Url scheme)
schm "http" = http
schm "https" = https
```

```bash
error:
    * Couldn't match type `scheme' with 'Http
      `scheme' is a rigid type variable bound by
        the type signature for:
          schm :: forall (scheme :: Scheme). String -> Text -> Url scheme   
        at src\Sut.hs:15:1-38
      Expected type: Text -> Url scheme
        Actual type: Text -> Url 'Http
    * In the expression: http
      In an equation for `schm': schm "http" = http
    * Relevant bindings include
        schm :: String -> Text -> Url scheme (bound at src\Sut.hs:16:1)     
   |
16 | schm "http" = http
   |               ^^^^
```

**Comment by mrkkrp** [comment]
In `req` we make a distinction between the two schemes at compile time. This means that after parsing of a `Url` you'll end up with different types for HTTP and HTTPS. Perhaps, [`useURI`](https://hackage.haskell.org/package/req-3.1.0/docs/Network-HTTP-Req.html#v:useURI) could be helpful.

**Comment by mrkkrp** [comment]
OK, let's say I've answered this one...

**Comment by mikesol** [comment]
Thanks for your help and sorry for the delay in responding!
