### ISSUE TITLE
How to pass GET, POST as a parameter to my function?

### ISSUE THREAD

**Issue by GildedHonour** [mrkkrp/req#79]
I have these functions which are identiacal except that one sends a GET request, the other POST one.

    send1 :: IO BS.ByteString
    send1 = do
        runReq defaultHttpConfig $ do
            result <- req GET (https "some_domain" /: "some_path") NoReqBody bsResponse getHeaders
            pure (responseBody result :: BS.ByteString)
        
        -- [some stuff...]

    send2 :: IO BS.ByteString
    send2 = do
        runReq defaultHttpConfig $ do
            result <- req POST (https "some_domain" /: "some_path") NoReqBody bsResponse getHeaders
            pure (responseBody result :: BS.ByteString)

        -- [some stuff]

I want to pass `GET` and `POST` as a parameter and thus merge the functions into a single one. I haven't found a way.

**Later on I might want to add PUT and DELETE too. For now I need only GET and POST**

`GET` and `POST` are both distinct data types in the library.

        data GET = GET
        data POST = POST

The `HttpMethod` class won't help either - it won't compile:

        send1 :: (HttpMethod meth) => meth -> IO BS.ByteString
        send1 meth = do
            runReq defaultHttpConfig $ do
                result <- req meth (https "some_domain" /: "some_path") NoReqBody bsResponse getHeaders
                pure (responseBody result :: BS.ByteString)

I don't want to create yet another new data type - `MyHttpMethod`, as a workaround, that'll have 2 constructors - `GET` and `POST`. I don't want to introduce new types.

Then how else?

**Comment by mrkkrp** [comment]
Why doesn't it work with `HttpMethod`?

**Comment by GildedHonour** [comment]
```
  • Could not deduce: HttpBodyAllowed (AllowsBody me) 'NoBody
        arising from a use of ‘req’
      from the context: HttpMethod me
        bound by the type signature for:
                   send12 :: forall me.
                            HttpMethod me => [..........]
```

**Comment by mrkkrp** [comment]
Then add `HttpBodyAllowed (AllowsBody me) 'NoBody` as a constraint to your function.

**Comment by GildedHonour** [comment]
Thanks.
