### ISSUE TITLE
How to do testing/mocking with req

### ISSUE THREAD

**Issue by anka-213** [mrkkrp/req#80]
This is more of a question than an issue. Do you know any good patterns for testing code that uses req, without actually connecting to the real server?

<sub>Sorry if this is the wrong place to ask and if my question is unclear. Thanks for a nice library!</sub>

**Comment by mrkkrp** [comment]
Depends. Do you want to inspect the request that `req` constructs or just want to make sure that in a certain situation a specific call will be performed? In the second case, the question is not specific to `req`, but rather to the way you abstract effects in your application.

You can try to look at `pure-tests` in the repo.

**Comment by anka-213** [comment]
Thanks! After looking at the pure-tests, it seems like they still use the IO monad despite being called pure, is there a reason for that?

---

Yes, I think what I want is to have tests against the exact body and headers that is generated and then return a bytestring that is parsed by req which returns it as if it came from the network, but that might be the wrong level of abstraction for tests.

I think one reason I asked this question was because of the `MonadHttp` typeclass, which I thought could almost be used for mocking if it wasn't for the `MonadIO` constraint, but I guess replacing it would needlessly complicate things, especially since that is not what it is for? I don't even know what `MonadIO` would be replaced by. 

Thank you for your patience!

**Comment by mrkkrp** [comment]
> Thanks! After looking at the pure-tests, it seems like they still use the IO monad despite being called pure, is there a reason for that?

They use `IO` but they do not make any calls. I think it wouldn't be possible to define `MonadHttp` for a pure monad.

I guess you could mostly follow the approach of `pure-tests` to see what is constructed.

Not sure about parsing part, that's handled by `http-client`.

**Comment by anka-213** [comment]
Thanks!
