### ISSUE TITLE
Hackage docs not working for 3.3.0

### ISSUE THREAD

**Issue by AlistairB** [mrkkrp/req#92]
Hi, seems that there is an issue with the hackage docs for the latest release. http://hackage.haskell.org/package/req-3.3.0/docs/Network-HTTP-Req.html is 404ing where https://hackage.haskell.org/package/req-3.2.0/docs/Network-HTTP-Req.html loads correctly.

**Comment by mrkkrp** [comment]
Apparently Hackage had attempted to build the docs but failed because there was not enough space left on the disk: https://hackage.haskell.org/package/req-3.3.0/reports/3.

I uploaded the docs manually.

**Comment by AlistairB** [comment]
Thanks!
