### ISSUE TITLE
How can I retry the request even if it errors out?

### ISSUE THREAD

**Issue by kindaro** [mrkkrp/req#93]
I have a problem that looks like this:

    *** Exception: HttpExceptionRequest Request {
      …
    (ConnectionFailure Network.Socket.connect: <socket: 12>: does not exist (Connection refused))

What happens is that I use Req to wait on some API to initialize. If I make an attempt to connect before the service opens the socket, everything falls apart, even though I use infinite retry policy.

I would like Req to retry according to the retry policy in case of a synchronous exception. Possibly a parameter can be added to `HttpConfig` with a type such as `[RetryStatus -> Handler m Bool]` that describes which exceptions should be caught? I am looking at functions such as [`recoverAll`][f] and I imagine there could be some way to bolt this functionality into Req.

[f]: https://hackage.haskell.org/package/retry-0.8.1.2/docs/Control-Retry.html#v:recoverAll

**Comment by mrkkrp** [comment]
Please see if https://github.com/mrkkrp/req/pull/96 fixes the problem.

**Comment by kindaro** [comment]
It works, I am going to use it.

I wish there was a way to add logging. [The `retry` library suggests that handlers be constructed with logging sewn in as desired.][retry] There is a beauty in keeping things pure too. It is not for me to opine on which design is preferable.

[retry]: https://hackage.haskell.org/package/retry-0.8.1.2/docs/Control-Retry.html#v:logRetries
