### ISSUE TITLE
Inspecting Request Created by `req` Function

### ISSUE THREAD

**Issue by patrotom** [mrkkrp/req#98]
Hi, I was wondering whether there is a canonical way to inspect a request created by the `req` function, which has not been run yet. Let's say I want to write a test suite where I want to test whether all the query parameters have been set properly, and the only thing I have is the output from the `req` function. I would be very glad if you could provide some code snippet. Thank you very much.

This is more of a question than an issue.

**Comment by mrkkrp** [comment]
Maybe you could use the approach I used in the test suite `pure-tests`?

**Comment by patrotom** [comment]
Yeah, that might work. Thank you!
